---
include:
  - board: eyelash_corne_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_corne_right
  - board: eyelash_corne_left
    shield: settings_reset
  - board: eyelash_corne_right
    shield: settings_reset
