parse_config:
  zmk_keycode_map:
    EXCL: "!"
    AT: "@"
    HASH: "#"
    DLLR: "$"
    PRCNT: "%"
    CARET: "^"
    AMPS: "&"
    ASTRK: "*"
    LPAR: "("
    RPAR: ")"
    MINUS: "-"
    EQUAL: "="
    LBKT: "["
    RBKT: "]"
    LBRC: "{"
    RBRC: "}"
    UNDER: "_"
    PLUS: "+"
    PIPE: "|"
    BSLH: "\\"
    TILDE: "~"
    GRAVE: "`"
    LT: "<"
    GT: ">"
    DQT: "\""
    SQT: "'"
    COLON: ":"
    SEMI: ";"
    QMARK: "?"
    FSLH: "/"
    COMMA: ","
    DOT: "."
    LGUI: "⌘"
    RGUI: "⌘"
    LALT: "⌥"
    RALT: "⌥"
    LCTRL: "⌃"
    RCTRL: "⌃"
    LSHFT: "⇧"
    RSHFT: "⇧"
    CAPS: "⇪"
    BSPC: "⌫"
    DEL: "⌦"
    TAB: "⇥"
    RET: "↵"
    ESC: "⎋"
    UP: "↑"
    DOWN: "↓"
    LEFT: "←"
    RIGHT: "→"
    PG_UP: "PgUp"
    PG_DN: "PgDn"
    HOME: "Home"
    END: "End"
    aero_1: "WS1"
    aero_2: "WS2"
    aero_3: "WS3"
    aero_4: "WS4"
    aero_5: "WS5"
    aero_6: "WS6"
    aero_7: "WS7"
    aero_8: "WS8"
    aero_9: "WS9"
    scr_full: "⌘⇧3"
    scr_sel: "⌘⇧4"
    hyper: "HYPER"
    tx_left: "←pane"
    tx_right: "→pane"
    tx_up: "↑pane"
    tx_down: "↓pane"
    tx_vsplit: "v-split"
    tx_hsplit: "h-split"
    tx_zoom: "zoom"
    tx_kill: "kill"
    tx_detach: "detach"
    tx_new: "new win"
    tx_next: "next win"
    tx_prev: "prev win"
    tx_last: "last pane"
    tx_sess: "sessions"
    tx_copy: "copy mode"
    tx_w1: "win 1"
    tx_w2: "win 2"
    tx_w3: "win 3"
    tx_w4: "win 4"
    tx_w5: "win 5"
    tx_w6: "win 6"
    tx_w7: "win 7"
    tx_w8: "win 8"
    tx_w9: "win 9"
    to_qwerty: "QWERTY"
    to_colemak: "CLMK"
    C_VOL_UP: "Vol+"
    C_VOL_DN: "Vol-"
    C_MUTE: "Mute"
    C_BRI_UP: "Bri+"
    C_BRI_DN: "Bri-"

draw_config:
  key_w: 55
  key_h: 45
  separate_combo_diagrams: true
  combo_diagrams_scale: 2
  layer_colors:
    - "#f8f8f8"
    - "#dff0ff"
    - "#dfffdf"
    - "#fff0df"
    - "#f0dfff"
    - "#ffdfdf"
    - "#dfffff"
    - "#ffffdf"
  trans_legend:
    t: "▽"
    type: "ghost"
