parse_config:
  zmk_keycode_map:
    # Symbols
    EXCL: "!"
    AT: "@"
    HASH: "#"
    DLLR: "$"
    PRCNT: "%"
    CARET: "^"
    AMPS: "&"
    ASTRK: "*"
    LPAR: "("
    RPAR: ")"
    MINUS: "-"
    EQUAL: "="
    LBKT: "["
    RBKT: "]"
    LBRC: "{"
    RBRC: "}"
    UNDER: "_"
    PLUS: "+"
    PIPE: "|"
    BSLH: "\\"
    TILDE: "~"
    GRAVE: "`"
    LT: "<"
    GT: ">"
    DQT: "\""
    SQT: "'"
    COLON: ":"
    SEMI: ";"
    QMARK: "?"
    FSLH: "/"
    COMMA: ","
    DOT: "."
    # Mods
    LGUI: "⌘"
    RGUI: "⌘"
    LALT: "⌥"
    RALT: "⌥"
    LCTRL: "⌃"
    RCTRL: "⌃"
    LSHFT: "⇧"
    RSHFT: "⇧"
    CAPS: "⇪"
    # Nav
    BSPC: "⌫"
    DEL: "⌦"
    TAB: "⇥"
    RET: "↵"
    ESC: "⎋"
    UP: "↑"
    DOWN: "↓"
    LEFT: "←"
    RIGHT: "→"
    PG_UP: "PgU"
    PG_DN: "PgD"
    HOME: "Home"
    END: "End"
    # AeroSpace
    aero_1: "WS1"
    aero_2: "WS2"
    aero_3: "WS3"
    aero_4: "WS4"
    aero_5: "WS5"
    aero_6: "WS6"
    aero_7: "WS7"
    aero_8: "WS8"
    aero_9: "WS9"
    # Screenshots
    scr_full: "⌘⇧3"
    scr_sel: "⌘⇧4"
    # Hyper
    hyper: "HYP"
    # Tmux pane nav
    tx_left: "←p"
    tx_right: "→p"
    tx_up: "↑p"
    tx_down: "↓p"
    # Tmux pane ops
    tx_vsplit: "v|"
    tx_hsplit: "h-"
    tx_zoom: "[]"
    tx_kill: "✕"
    tx_detach: "det"
    # Tmux window ops
    tx_new: "+win"
    tx_next: "n›"
    tx_prev: "‹p"
    tx_last: "last"
    tx_sess: "sess"
    tx_copy: "copy"
    # Tmux windows
    tx_w1: "w1"
    tx_w2: "w2"
    tx_w3: "w3"
    tx_w4: "w4"
    tx_w5: "w5"
    tx_w6: "w6"
    tx_w7: "w7"
    tx_w8: "w8"
    tx_w9: "w9"
    # Layout
    to_qwerty: "QWY"
    to_colemak: "CLM"
    # Media
    C_VOL_UP: "V+"
    C_VOL_DN: "V-"
    C_MUTE: "mut"
    C_BRI_UP: "B+"
    C_BRI_DN: "B-"
    # Mouse
    MOVE_UP: "↑"
    MOVE_DOWN: "↓"
    MOVE_LEFT: "←"
    MOVE_RIGHT: "→"
    SCRL_UP: "⬆"
    SCRL_DOWN: "⬇"
    LCLK: "L"
    RCLK: "R"
    MCLK: "M"
    # RGB
    RGB_TOG: "RGB"
    RGB_BRI: "R+"
    RGB_BRD: "R-"
    RGB_EFF: "FX"
    RGB_HUI: "H+"
    RGB_HUD: "H-"
    RGB_SAI: "S+"
    RGB_SAD: "S-"
    RGB_SPI: "Sp+"
    RGB_SPD: "Sp-"

draw_config:
  key_w: 55
  key_h: 45
  separate_combo_diagrams: true
  combo_diagrams_scale: 2
  layer_colors:
    - "#f8f8f8"
    - "#dff0ff"
    - "#dfffdf"
    - "#fff0df"
    - "#f0dfff"
    - "#ffdfdf"
    - "#dfffff"
    - "#ffffdf"
  trans_legend:
    t: "▽"
    type: "ghost"
