manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nickcoutsos
      url-base: https://github.com/nickcoutsos
    - name: maatthc
      url-base: https://github.com/maatthc
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-feature-appcompanion
      remote: maatthc
      revision: main
    - name: keyboardio-hid
      remote: nickcoutsos
      revision: main
  self:
    path: config
