name: Draw ZMK keymaps

on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install keymap-drawer
        run: pipx install keymap-drawer
      - name: Parse and draw keymap
        run: |
          mkdir -p keymap-drawer
          keymap -c keymap_drawer.config.yaml parse -z config/eyelash_corne.keymap > keymap-drawer/eyelash_corne.yaml
          keymap -c keymap_drawer.config.yaml draw \
            -l default_layout \
            keymap-drawer/eyelash_corne.yaml > keymap-drawer/eyelash_corne.svg
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "keymap-drawer render"
          file_pattern: "keymap-drawer/*.svg keymap-drawer/*.yaml"
